owner: jtsimoes
repo: upptime

sites:
  - name: Agora Aveiro
    url: https://agoraaveiro.org
    maxResponseTime: 2000
  - name: Private website
    url: $PRIVATE_WEBSITE

status-website:
  cname: jtsimoes.com
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  theme: night
  introTitle: " "
  introMessage: " "
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex, nofollow"
